from __future__ import annotations

import xml.etree.ElementTree as ET

from jmdict_normalization import text_values

USAGE_LABELS: dict[str, str] = {
    "abbr": "abbreviation",
    "arch": "archaic",
    "char": "character",
    "chn": "childrensLanguage",
    "col": "colloquial",
    "company": "companyName",
    "creat": "creature",
    "dated": "dated",
    "dei": "deity",
    "derog": "derogatory",
    "doc": "document",
    "euph": "euphemistic",
    "ev": "event",
    "fam": "familiar",
    "fem": "feminine",
    "fict": "fiction",
    "form": "formal",
    "given": "givenName",
    "group": "group",
    "hist": "historical",
    "hon": "honorific",
    "hum": "humble",
    "id": "idiomatic",
    "joc": "jocular",
    "leg": "legend",
    "m-sl": "mangaSlang",
    "male": "masculine",
    "myth": "mythology",
    "net-sl": "internetSlang",
    "obj": "object",
    "obs": "obsolete",
    "on-mim": "onomatopoeic",
    "organization": "organizationName",
    "oth": "other",
    "person": "personName",
    "place": "placeName",
    "poet": "poetic",
    "pol": "polite",
    "product": "productName",
    "proverb": "proverb",
    "quote": "quotation",
    "rare": "rare",
    "relig": "religion",
    "sens": "sensitive",
    "serv": "service",
    "ship": "shipName",
    "sl": "slang",
    "station": "railwayStation",
    "surname": "surname",
    "uk": "usuallyKana",
    "unclass": "unclassifiedName",
    "vulg": "vulgar",
    "work": "workTitle",
    "X": "rude",
    "yoji": "yojijukugo",
}

SUBJECT_FIELDS: dict[str, str] = {
    "agric": "agriculture",
    "anat": "anatomy",
    "archeol": "archeology",
    "archit": "architecture",
    "art": "art",
    "astron": "astronomy",
    "audvid": "audiovisual",
    "aviat": "aviation",
    "baseb": "baseball",
    "biochem": "biochemistry",
    "biol": "biology",
    "bot": "botany",
    "boxing": "boxing",
    "Buddh": "buddhism",
    "bus": "business",
    "cards": "cardGames",
    "chem": "chemistry",
    "chmyth": "chineseMythology",
    "Christn": "christianity",
    "civeng": "civilEngineering",
    "cloth": "clothing",
    "comp": "computing",
    "cryst": "crystallography",
    "dent": "dentistry",
    "ecol": "ecology",
    "econ": "economics",
    "elec": "electricalEngineering",
    "electr": "electronics",
    "embryo": "embryology",
    "engr": "engineering",
    "ent": "entomology",
    "figskt": "figureSkating",
    "film": "film",
    "finc": "finance",
    "fish": "fishing",
    "food": "food",
    "gardn": "gardening",
    "genet": "genetics",
    "geogr": "geography",
    "geol": "geology",
    "geom": "geometry",
    "go": "go",
    "golf": "golf",
    "gramm": "grammar",
    "grmyth": "greekMythology",
    "hanaf": "hanafuda",
    "horse": "horseRacing",
    "internet": "internet",
    "jpmyth": "japaneseMythology",
    "kabuki": "kabuki",
    "law": "law",
    "ling": "linguistics",
    "logic": "logic",
    "MA": "martialArts",
    "mahj": "mahjong",
    "manga": "manga",
    "math": "mathematics",
    "mech": "mechanicalEngineering",
    "med": "medicine",
    "met": "meteorology",
    "mil": "military",
    "min": "mineralogy",
    "mining": "mining",
    "motor": "motorsport",
    "music": "music",
    "noh": "noh",
    "ornith": "ornithology",
    "paleo": "paleontology",
    "pathol": "pathology",
    "pharm": "pharmacology",
    "phil": "philosophy",
    "photo": "photography",
    "physics": "physics",
    "physiol": "physiology",
    "politics": "politics",
    "print": "printing",
    "prowres": "professionalWrestling",
    "psy": "psychiatry",
    "psyanal": "psychoanalysis",
    "psych": "psychology",
    "rail": "railway",
    "rommyth": "romanMythology",
    "Shinto": "shinto",
    "shogi": "shogi",
    "ski": "skiing",
    "sports": "sports",
    "stat": "statistics",
    "stockm": "stockMarket",
    "sumo": "sumo",
    "surg": "surgery",
    "telec": "telecommunications",
    "tradem": "trademark",
    "tv": "television",
    "vet": "veterinary",
    "vidg": "videoGames",
    "zool": "zoology",
}

DIALECTS: dict[str, str] = {
    "bra": "brazilian",
    "hob": "hokkaido",
    "ksb": "kansai",
    "ktb": "kanto",
    "kyb": "kyoto",
    "kyu": "kyushu",
    "nab": "nagano",
    "osb": "osaka",
    "rkb": "ryukyu",
    "thb": "tohoku",
    "tsb": "tosa",
    "tsug": "tsugaru",
}

SENSE_LABEL_KINDS = (
    ("usage", "misc", USAGE_LABELS),
    ("fields", "field", SUBJECT_FIELDS),
    ("dialects", "dial", DIALECTS),
)


def sense_labels(sense: ET.Element, entity_codes: dict[str, str]) -> dict[str, list[str]]:
    labels: dict[str, list[str]] = {}
    for key, element, vocabulary in SENSE_LABEL_KINDS:
        identifiers: list[str] = []
        for provider_label in text_values(sense, element):
            code = entity_codes.get(provider_label)
            identifier = vocabulary.get(code or "")
            if identifier is None:
                raise ValueError(f"unmapped JMdict {element} label: {code or provider_label}")
            if identifier not in identifiers:
                identifiers.append(identifier)
        if identifiers:
            labels[key] = identifiers
    return labels
