// Throwaway: three dictionary designs on /?variant=A|B|C. Question: which hierarchy makes entries easiest to read?
import { useEffect, useState, type ReactNode } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowLeft, ArrowRight, Search, Volume2, BookOpen, ChevronRight } from 'lucide-react';
import { Card, CardHeader, CardContent, Switch } from './ui';
import './style.css';

type Entry = { word:string; reading:string; romaji:string; gloss:string; pos:string; frequency:string; pitch:string; pattern:number[]; mora:string[]; example?:[string,string] };
const entries:Entry[] = [
 {word:'昨日',reading:'きのう',romaji:'kinō',gloss:'yesterday',pos:'Noun · Adverb',frequency:'#460',pitch:'Heiban · 0',pattern:[0,1,1],mora:['き','の','う'],example:['昨日はとても楽しかった。','Yesterday was a lot of fun.']},
 {word:'今日',reading:'きょう',romaji:'kyō',gloss:'today; this day',pos:'Noun · Adverb',frequency:'#102',pitch:'Atamadaka · 1',pattern:[1,0],mora:['きょ','う'],example:['今日はいい天気ですね。','It’s a beautiful day today, isn’t it?']},
 {word:'明日',reading:'あした',romaji:'ashita',gloss:'tomorrow',pos:'Noun · Adverb',frequency:'#317',pitch:'Heiban · 0',pattern:[0,1,1],mora:['あ','し','た'],example:['明日、また会いましょう。','Let’s meet again tomorrow.']},
 {word:'毎日',reading:'まいにち',romaji:'mainichi',gloss:'every day; daily',pos:'Noun · Adverb',frequency:'#684',pitch:'Atamadaka · 1',pattern:[1,0,0,0],mora:['ま','い','に','ち'],example:['毎日、日本語を勉強しています。','I study Japanese every day.']},
 {word:'時間',reading:'じかん',romaji:'jikan',gloss:'time; hours',pos:'Noun',frequency:'#95',pitch:'Heiban · 0',pattern:[0,1,1],mora:['じ','か','ん']},
 {word:'今週',reading:'こんしゅう',romaji:'konshū',gloss:'this week',pos:'Noun · Adverb',frequency:'#1208',pitch:'Heiban · 0',pattern:[0,1,1,1],mora:['こ','ん','しゅ','う'],example:['今週は忙しいです。','I’m busy this week.']},
];
const names = {A:'Quiet index',B:'Field notes',C:'Open book'};
type Variant=keyof typeof names;
function getVariant():Variant { const v=new URLSearchParams(location.search).get('variant');return v==='B'||v==='C'?v:'A'; }
function App(){
 const [variant,setVariant]=useState<Variant>(getVariant),[romaji,setRomaji]=useState(true),[furigana,setFurigana]=useState(true),[draft,setDraft]=useState(''),[query,setQuery]=useState(''),[audio,setAudio]=useState('');
 function cycle(delta:number){setVariant(v=>{const next=(['A','B','C'] as Variant[])[(('ABC'.indexOf(v)+delta)+3)%3];const u=new URL(location.href);u.searchParams.set('variant',next);history.replaceState(null,'',u);return next;});}
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,textarea,[contenteditable="true"]'))return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();cycle(e.key==='ArrowLeft'?-1:1);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const list=query?entries.filter(e=>`${e.word} ${e.reading} ${e.romaji} ${e.gloss}`.toLowerCase().includes(query.toLowerCase().trim())):entries;
 function speak(e:Entry){if(!('speechSynthesis' in window)){setAudio('Speech preview is unavailable in this browser.');return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(e.reading);u.lang='ja-JP';u.rate=.8;u.onstart=()=>setAudio(`Playing ${e.word} with device speech`);u.onend=()=>setAudio(`Finished ${e.word} · device speech`);u.onerror=()=>setAudio('Device speech could not play. A Japanese voice may be unavailable.');setAudio(`Requesting device speech for ${e.word}…`);speechSynthesis.speak(u);}
 const search=<div className="search-area"><form className="searchbox" onSubmit={e=>{e.preventDefault();setQuery(draft.trim());}}><Search size={21}/><input aria-label="Search Japanese dictionary" placeholder="Japanese, romaji, or English" value={draft} onChange={e=>setDraft(e.target.value)}/><button type="submit">Search <ArrowRight size={17}/></button></form><div className="reading-controls"><label htmlFor="romaji">Romaji <Switch id="romaji" checked={romaji} onCheckedChange={setRomaji}/></label><label htmlFor="furigana">Furigana <Switch id="furigana" checked={furigana} onCheckedChange={setFurigana}/></label></div></div>;
 function Word({entry}:{entry:Entry}){return <div className="word"><h2 lang="ja"><ruby>{entry.word}{furigana&&<rt>{entry.reading}</rt>}</ruby></h2>{romaji&&<p className="romaji">{entry.romaji}</p>}</div>;}
 function Sound({entry}:{entry:Entry}){return <div className="sound"><div className="pitch" aria-label={`Pitch accent: ${entry.pitch}`}><svg width={entry.pattern.length*22} height="26" viewBox={`0 0 ${entry.pattern.length*22} 26`} aria-hidden="true"><polyline points={entry.pattern.map((x,i)=>`${i*22+8},${x?5:21}`).join(' ')} fill="none" stroke="currentColor" strokeWidth="1.5"/>{entry.pattern.map((x,i)=><circle key={i} cx={i*22+8} cy={x?5:21} r="3" fill="currentColor"/>)}</svg><span lang="ja">{entry.mora.join(' ')}</span></div><div className="pitch-label">{entry.pitch}</div><button className="speaker" aria-label={`Play ${entry.word} with device speech`} title="Device speech preview; does not reproduce the pitch diagram" onClick={()=>speak(entry)}><Volume2 size={18}/></button></div>;}
 function Example({entry}:{entry:Entry}){return entry.example?<div className="example"><p lang="ja">{entry.example[0]}</p><p>{entry.example[1]}</p></div>:null;}
 function EntryCard({entry,mode}:{entry:Entry;mode:Variant}){return <Card className={`entry entry-${mode}`}><CardHeader><Word entry={entry}/><span className="frequency" title="Illustrative frequency rank">{entry.frequency} <span>frequency</span></span></CardHeader><CardContent><div className="meaning"><span className="pos">{entry.pos}</span><h3>{entry.gloss}</h3></div><Sound entry={entry}/><Example entry={entry}/></CardContent></Card>;}
 const cards=(mode:Variant)=>list.map(e=><EntryCard entry={e} mode={mode} key={e.word}/>);
 const resultsHeading=<div className="results-heading"><h2>{query?`Matches for “${query}”`:'A little Japanese, every day.'}</h2><span>{list.length} {query?'matches':'everyday words'}</span></div>;
 const empty=list.length===0?<Card className="empty"><h2>No fixture matches</h2><p>Try “yesterday”, “今日”, or “jikan”.</p><button onClick={()=>{setDraft('');setQuery('');}}>Show all words</button></Card>:null;
 function Header(){return <header><a className="brand" href={`/?variant=${variant}`}><span className="brand-mark">ぜ</span><span>zenbu<span className="brand-sub">JAPANESE</span></span></a><span className="nav-label"><BookOpen size={16}/> Dictionary</span><a className="nav-about" href="#about">About this preview <ChevronRight size={14}/></a></header>;}
 function VariantA(){return <><Header/><section className="hero hero-a"><span className="eyebrow">YOUR EVERYDAY JAPANESE DICTIONARY</span><h1>Make sense of<br/><em>every word.</em></h1><p>Clear meanings. A little context. Keep discovering.</p>{search}</section><main className="main-a">{resultsHeading}<div className="entries">{cards('A')}</div>{empty}</main></>;}
 function VariantB(){return <><Header/><section className="hero hero-b"><div className="hero-copy"><span className="eyebrow">WORDS OPEN WORLDS</span><h1>Find your<br/>next word<span className="dot">.</span></h1><p>A Japanese dictionary for the curious.</p></div><div className="hero-search">{search}<span className="search-tip">Try 昨日, kinō, or yesterday</span></div></section><main className="main-b">{resultsHeading}<div className="entries">{cards('B')}</div>{empty}</main></>;}
 function VariantC(){return <><Header/><section className="hero hero-c"><span className="eyebrow">THE JAPANESE DICTIONARY</span><h1>One word.<br/><span>A world of meaning.</span></h1>{search}</section><main className="main-c"><aside><span className="eyebrow">ON THIS PAGE</span><h2>{query?'Your matches':'Everyday essentials'}</h2><p>{query?`Exploring “${query}”`:'Words for the days that make up a life.'}</p><span className="result-count">{list.length} entries</span></aside><div className="entries">{cards('C')}{empty}</div></main></>;}
 const components:Record<Variant,()=>ReactNode>={A:VariantA,B:VariantB,C:VariantC};
 return <div className={`site variant-${variant}`}>{components[variant]()}<footer id="about"><span>ぜんぶ、ここから。<br/><strong>Every word is a beginning.</strong></span><p>Design preview · six illustrative entries.<br/>Frequency and pitch are sample data. Audio uses device speech,<br/>which may not match the pitch diagram.</p></footer><div className="audio-status" role="status">{audio}</div>{import.meta.env.DEV&&<div className="prototype-bar"><button aria-label="Previous design" onClick={()=>cycle(-1)}><ArrowLeft size={16}/></button><div><strong>SET TWO · {variant} — {names[variant]}</strong><small>Romaji {romaji?'on':'off'} · Furigana {furigana?'on':'off'} · {list.length} entries</small></div><button aria-label="Next design" onClick={()=>cycle(1)}><ArrowRight size={16}/></button></div>}</div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
