// Throwaway: three dictionary layouts, shareable on /?variant=A|B|C. Issue #298.
import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter, useSearchParams} from 'react-router-dom';
import {ArrowLeft, ArrowRight, Search, Volume2, BookOpen, ArrowUpRight} from 'lucide-react';
import {Card, Switch} from './ui';
import './style.css';

const entries=[
 {word:'昨日',reading:'きのう',romaji:'kinō',definition:'yesterday',pos:'Noun · Adverb',frequency:349,pitch:'0 · Heiban',mora:['き','の','う'],pattern:[0,1,1],example:'昨日はいい天気でした。',translation:'The weather was nice yesterday.'},
 {word:'今日',reading:'きょう',romaji:'kyō',definition:'today; this day',pos:'Noun · Adverb',frequency:128,pitch:'1 · Atamadaka',mora:['きょ','う'],pattern:[1,0],example:'今日は何をしますか。',translation:'What are you doing today?'},
 {word:'明日',reading:'あした',romaji:'ashita',definition:'tomorrow',pos:'Noun · Adverb',frequency:263,pitch:'3 · Odaka',mora:['あ','し','た'],pattern:[0,1,1],example:'また明日会いましょう。',translation:'Let’s meet again tomorrow.'},
 {word:'毎日',reading:'まいにち',romaji:'mainichi',definition:'every day; daily',pos:'Noun · Adverb',frequency:650,pitch:'1 · Atamadaka',mora:['ま','い','に','ち'],pattern:[1,0,0,0],example:'毎日、日本語を勉強します。',translation:'I study Japanese every day.'},
 {word:'週末',reading:'しゅうまつ',romaji:'shūmatsu',definition:'weekend',pos:'Noun',frequency:2138,pitch:'0 · Heiban',mora:['しゅ','う','ま','つ'],pattern:[0,1,1,1]},
 {word:'時間',reading:'じかん',romaji:'jikan',definition:'time; hour; duration',pos:'Noun',frequency:110,pitch:'0 · Heiban',mora:['じ','か','ん'],pattern:[0,1,1],example:'少し時間があります。',translation:'I have a little time.'}
];
const names={A:'Quiet dictionary',B:'Reading room',C:'Word collection'};
type Entry=typeof entries[number];
function App(){
 const [params,setParams]=useSearchParams(); const key=params.get('variant');const variant=(key==='B'||key==='C'?key:'A') as keyof typeof names;
 const [romaji,setRomaji]=useState(true),[furigana,setFurigana]=useState(true),[query,setQuery]=useState(''),[status,setStatus]=useState('');
 const results=entries.filter(e=>[e.word,e.reading,e.romaji,e.definition].some(s=>s.toLowerCase().includes(query.trim().toLowerCase())));
 const cycle=(n:number)=>setParams({variant:['A','B','C'][(['A','B','C'].indexOf(variant)+n+3)%3]});
 useEffect(()=>{function keydown(e:KeyboardEvent){if((e.target as HTMLElement).closest('input,textarea,[contenteditable="true"],[role="switch"]'))return;if(e.key==='ArrowRight')cycle(1);if(e.key==='ArrowLeft')cycle(-1);}window.addEventListener('keydown',keydown);return()=>window.removeEventListener('keydown',keydown);},[variant]);
 function speak(e:Entry){if(!('speechSynthesis'in window)){setStatus('Device speech is unavailable in this browser.');return;}const voices=speechSynthesis.getVoices();const japanese=voices.find(v=>v.lang.startsWith('ja'));if(!japanese){setStatus('No Japanese device voice is installed. Audio preview unavailable.');return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(e.word);u.lang='ja-JP';u.voice=japanese;u.rate=.8;u.onend=()=>setStatus(`Device voice preview finished: ${e.word}`);u.onerror=()=>setStatus('Device voice preview unavailable.');speechSynthesis.speak(u);setStatus(`Playing device voice: ${e.word}. Pitch may differ from the diagram.`);}
 useEffect(()=>{if('speechSynthesis'in window)speechSynthesis.getVoices();},[]);
 const search=<div className="search-area"><form onSubmit={e=>e.preventDefault()} className="search-box"><Search size={21}/><input aria-label="Search dictionary" placeholder="Search Japanese, romaji, or English" value={query} onChange={e=>setQuery(e.target.value)}/><button type="submit" aria-label="Search"><ArrowRight size={20}/></button></form><div className="reading-controls"><label htmlFor="romaji"><Switch id="romaji" checked={romaji} onCheckedChange={setRomaji}/>Romaji</label><label htmlFor="furigana"><Switch id="furigana" checked={furigana} onCheckedChange={setFurigana}/>Furigana</label><span className="control-note">Read your way</span></div></div>;
 const cards=results.map((e,i)=><EntryCard key={e.word} e={e} index={i} romaji={romaji} furigana={furigana} speak={speak}/>);
 const resultHeading=<div className="result-heading"><h2>{query?`Results for “${query}”`:'A little Japanese, every day.'}</h2><span>{results.length} words</span></div>;
 return <div className={`page variant-${variant}`}><header><a className="brand" href={`/?variant=${variant}`}><span className="brand-mark">全</span>zenbu<span className="brand-label">Japanese dictionary</span></a><span className="header-note">Words open worlds.</span><span className="demo-badge">Dictionary preview</span></header>
 {variant==='A'?<VariantA search={search} heading={resultHeading} cards={cards}/>:variant==='B'?<VariantB search={search} heading={resultHeading} cards={cards}/>:<VariantC search={search} heading={resultHeading} cards={cards}/>}
 {results.length===0?<div className="empty">No fixture words found. Try “today”, “昨日”, or clear your search.</div>:null}
 <footer><span>ぜんぶ · All the words, a little clearer.</span><span>Sample entries · illustrative frequency ranks · device audio</span></footer><div role="status" className="audio-status">{status}</div>
 {import.meta.env.DEV?<div className="prototype-switcher"><button aria-label="Previous design" onClick={()=>cycle(-1)}><ArrowLeft size={16}/></button><div><strong>SET 1 · {variant} — {names[variant]}</strong><small>Romaji {romaji?'on':'off'} · Furigana {furigana?'on':'off'} · {results.length} results</small></div><button aria-label="Next design" onClick={()=>cycle(1)}><ArrowRight size={16}/></button></div>:null}</div>;
}
function VariantA({search,heading,cards}:any){return <><section className="hero"><div className="eyebrow">JAPANESE, WITH CLARITY</div><h1>Find the word.<br/><span>Keep the meaning.</span></h1><p>A small space for your next discovery.</p>{search}</section><main>{heading}<div className="entries">{cards}</div></main></>}
function VariantB({search,heading,cards}:any){return <><section className="hero"><div className="hero-copy"><div className="eyebrow">THE EVERYDAY DICTIONARY</div><h1>A word.<br/>A whole world.</h1><p>Meaning, sound, and a little context.<br/>Make Japanese part of your day.</p></div><div className="hero-search"><BookOpen size={27}/><h2>What are you curious about?</h2>{search}</div></section><main><aside><span className="eyebrow">ON THESE PAGES</span><h2>Days &<br/>moments.</h2><p>Useful words for the time we spend, and the plans we make.</p><span className="aside-note">06 / SAMPLE WORDS</span></aside><div className="results">{heading}<div className="entries">{cards}</div></div></main></>}
function VariantC({search,heading,cards}:any){return <><section className="hero"><div className="eyebrow">YOUR JAPANESE COMPANION</div><h1>One word closer.</h1><p>Find a meaning. Hear a sound. See it in a sentence.</p>{search}<div className="hero-caption"><span>日本語 → English</span><span>Made for the curious <ArrowUpRight size={13}/></span></div></section><main>{heading}<div className="entries">{cards}</div></main></>}
function EntryCard({e,index,romaji,furigana,speak}:{e:Entry,index:number,romaji:boolean,furigana:boolean,speak:(e:Entry)=>void}){return <Card className="entry"><div className="word-column"><span className="entry-index">{String(index+1).padStart(2,'0')}</span><h3 lang="ja"><ruby>{e.word}{furigana?<rt>{e.reading}</rt>:null}</ruby></h3>{romaji?<p className="romaji">{e.romaji}</p>:null}<span className="frequency">Frequency <strong>#{e.frequency.toLocaleString()}</strong></span></div><div className="meaning-column"><div className="entry-topline"><span className="pos">{e.pos}</span><span className="common">Common word</span></div><p className="definition">{e.definition}</p><div className="pronunciation"><button onClick={()=>speak(e)} aria-label={`Play device voice for ${e.word}`} title="Device TTS preview; not a pitch recording"><Volume2 size={17}/></button><div className="pitch" aria-label={`Pitch accent ${e.pitch}`}><div className="moras">{e.mora.map((m,i)=><span key={i} className={e.pattern[i]?'high':'low'}>{m}</span>)}</div><span>{e.pitch}</span></div><small>Device voice</small></div>{e.example?<div className="example"><p lang="ja">{e.example}</p><p>{e.translation}</p></div>:null}</div></Card>}
createRoot(document.getElementById('root')!).render(<BrowserRouter><App/></BrowserRouter>);
